COLUMNS:
  EmpNumber: "str"
  Age: "int"
  Gender: "str"
  EducationBackground: "str"
  MaritalStatus: "str"
  EmpDepartment: "str"
  EmpJobRole: "str"
  BusinessTravelFrequency: "str"
  DistanceFromHome: "int"
  EmpEducationLevel: "int"
  EmpEnvironmentSatisfaction: "int"
  EmpHourlyRate: "int"
  EmpJobInvolvement: "int"
  EmpJobLevel: "int"
  EmpJobSatisfaction: "int"
  NumCompaniesWorked: "int"
  OverTime: "str"
  EmpLastSalaryHikePercent: "int"
  EmpRelationshipSatisfaction: "int"
  TotalWorkExperienceInYears: "int"
  TrainingTimesLastYear: "int"
  EmpWorkLifeBalance: "int"
  ExperienceYearsAtThisCompany: "int"
  ExperienceYearsInCurrentRole: "int"
  YearsSinceLastPromotion: "int"
  YearsWithCurrManager: "int"
  Attrition: "str"
  PerformanceRating: "int"
TARGET_COLUMN:
  name: target